### ISSUE TITLE
Gazebo Playback Missing WAM-V

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx-docker#1]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx-docker/issues/1)) by Tyler Lum (Bitbucket: [tylerlum](https://bitbucket.org/%7B305d9368-23ba-4f72-b1d4-7d17d2a062d8%7D/)).**

----------------------------------------
**Description**

Currently, the Gazebo simulation playback log files are being created and saved onto the host computer. The issue is that when these files are played, the WAM-V is not visible. It is still listed as one of the Models on the Gazebo GUI, but right-clicking > Move to moves to a location where the boat is not visible.

**Instructions to Recreate**

1. Move to `vrx-docker`
2. Run `./prepare_team_wamv.bash example_team && ./prepare_task_trials.bash example_task && ./vrx_server/build_image.bash && ./run_trial.bash example_team example_task 0`
3. Playback with `roslaunch vrx_gazebo playback.launch log_file:=/home/tylerlum/vrx-docker/logs/<recent date>/gazebo-server/log/<data>/state.log` <path to log file>

**Comment by M1chaelM** [comment]
This issue was made obsolete with PR #31, which eliminates the need to call playback.launch directly, and also the requirement to run it on the host. Instead, the `reply_trial.bash` script now calls the `play_vrx_log.sh` within the container, which calls playback.launch inside the container.
