### ISSUE TITLE
station_keeping.yaml and wayfinding.yaml have the wrong number of steps

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx-docker#10]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx-docker/issues/10)) by Michael McCarrin (Bitbucket: [m1chaelm](https://bitbucket.org/%7B3c3f500d-bbf6-472c-b8f7-627e5eabc226%7D/)).**

----------------------------------------
These files both have 1 step but 2 sequences. The second sequence gets ignored. This is a problem if people are reading these files as examples of how to write their own, since it is confusing.

Do we intend to generate only one world, or should we increment the step number?

**Comment by M1chaelM** [comment]
Closing because this issue is obsolete. Both files have been since been updated so all sequences are used.
