### ISSUE TITLE
oyaml dependency

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx-docker#11]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx-docker/issues/11)) by Brian Bingham (Bitbucket: [brian_bingham](https://bitbucket.org/%7B9cdea257-248f-486e-8858-49d8485a916f%7D/)).**

----------------------------------------
We discussed removing the oyaml dependency listed in [README.md](http://README.md)

 `pip install oyaml` - for generating wam-v and worlds

I believe the default yaml library is sufficient and this avoids using pip, which we are not using in other parts of the project.

**Comment by M1chaelM** [comment]
Since the Python scripts for generating the wamv and worlds are part of the VRX repository, this dependency should really have been listed in VRX installation instructions. Dependence on oyaml was removed in v1.2.1, but the vrx-docker README was not updated.

**Comment by M1chaelM** [comment]
This is now fixed with PR #43
