### ISSUE TITLE
Figure out if Server or Competitor Image Starts First

### ISSUE THREAD

**Issue by osrf-migration** [osrf/vrx-docker#7]
**Original report ([archived issue](https://osrf-migration.github.io/vrx-gh-pages/#!/osrf/vrx-docker/issues/7)) by Tyler Lum (Bitbucket: [tylerlum](https://bitbucket.org/%7B305d9368-23ba-4f72-b1d4-7d17d2a062d8%7D/)).**

----------------------------------------
As of right now, the simulation server container is created first before the competitor container, but we should figure out if this is the right approach

Pros of Server First

* The server creates the ROS master, which should be created before the competitor’s container is run to prevent error messages and possible errors in competitor container that prevents it from running correctly

Cons of Server First

* If slow to start, competition might start before competitor container is created. This would mean the competitor would be at a disadvantage if their software starts too late. \(should be okay with the ready time\)

‌

Pros of Client First

* ARIAC had the competitor’s container start first, likely to ensure that the competition didn’t somehow start early before the competitor container had even been run

Cons of Client First

* ROS Master not created, will have error message

‌

I believe that the ready time before the competition is long enough, but we should test it to be sure.

The important thing is to make sure that this ordering makes no impact on the competition.

**Comment by M1chaelM** [comment]
There is not an obvious way to guarantee this in general because the competitor container can take arbitrarily long to start. However, I think it is reasonably accounted for by giving teams access to the testing infrastructure and conducting the "dress rehearsal" phase.
